"use client"
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css"
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import StoreProvider from "@/lib/redux/StoreProvider";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isAdmin = pathname.startsWith("/admin");
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
        <StoreProvider>
          {/* Sticky Header */}
          {!isAdmin &&
          <div className="sticky top-0 z-50 shadow-md">
            <Header />
          </div>
}

          {/* Main Content */}

          <main className="overflow-hidden">
            {children}
            {/* <StoreProvider>{children}</StoreProvider> */}
          </main>
 {!isAdmin && 
         
          <Footer />
 }
        </StoreProvider>

      </body>
    </html>
  );
}
